services:
  live-match:
    build:
      context: live-match
      target: dev
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/msgotest1
    ports:
      - 3000:3000
    volumes:
      - ./live-match/src:/usr/src/app/src
    restart: always

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    command: mongod --quiet --logpath /dev/null 

volumes:
  dbdata: