version: '3'

services:
  front-end:
    image: front-end:latest
    ports:
      - "8080:8080"
    environment:
      - USER_MANAGEMENT_API=http://user-management:4050
      - SESSION_SECRET=secret

  user-management:
    image: user-management:latest
    ports:
      - "4050:4050"
    environment:
      - TOKEN_SECRET=secret
      - DB_CONNECT=mongodb://userdatabase:27017/users
    depends_on:
      - userdatabase

  userdatabase:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    command: --quiet

