apiVersion: apps/v1
kind: Deployment
metadata:
  name: msgo
  namespace: default
spec:
  selector:
    matchLabels:
      app: msgo
  template:
    metadata:
      labels:
        app: msgo
    spec:
      containers:
      - name: msgo
        image: jlukassamby/live-match
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: msgo-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: msgo
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
